export const languageOptions = [
    { label: "Hindi", value: "hi" },
    { label: "English", value: "en" },
    { label: "Bengali", value: "bn" },
    { label: "Telugu", value: "te" },
    { label: "Marathi", value: "mr" },
    { label: "Tamil", value: "ta" },
    { label: "Gujarati", value: "gu" },
    { label: "Kannada", value: "kn" },
    { label: "Malayalam", value: "ml" },
    { label: "Punjabi", value: "pa" },
    { label: "Odia", value: "or" },
    { label: "Assamese", value: "as" },
    { label: "Maithili", value: "mai" },
    { label: "Sanskrit", value: "sa" },
    { label: "Konkani", value: "kok" },
    { label: "Manipuri (Meitei)", value: "mni" },
    { label: "Bodo", value: "brx" },
    { label: "Dogri", value: "doi" },
    { label: "Santhali", value: "sat" },
    { label: "Kashmiri", value: "ks" },
    { label: "Sindhi", value: "sd" },
    { label: "Urdu", value: "ur" }
];
